version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "/app/wait-for-it.sh db:5432 --timeout=90 -- flask db init && flask db migrate && flask run --host 0.0.0.0 --port 5000 --reload"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`thatta-api.duckdns.org`)"
      - "traefik.http.routers.app.entrypoints=web"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DOCKER_ENV=True
    networks:
      - web

  db:
    image: postgres:13
    restart: always
    environment:
      - DOCKER_ENV=True
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tata
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web

volumes:
  db_data:

networks:
  web:
    external: true
