from controllers.clientes import ClientesController
from controllers.consultas_juridicas import ConsultaJuridicaController
from controllers.users import UserController
from controllers.documentos import DocumentoController